### ISSUE TITLE
Grammar typo in handleActions.js

### ISSUE THREAD

**Issue by kanitw** [reduxactions/redux-actions#234] opened 2017-07-26 00:14 UTC
I was reading your readme.md in https://github.com/acdlite/reduce-reducers which point to this file

https://github.com/acdlite/redux-actions/blob/master/src/handleActions.js#L11

>     'Expected handlers to be an plain object.'
I guess this should be "a plain object"?  

I hope this is helpful! :)

**Comment by yangmillstheory** [comment] 2017-07-26 00:49
It's helpful, a PR would be more helpful

**Comment by mslipper** [comment] 2018-01-16 04:02
Closing this since the issue is fixed.

**Closed by mslipper** 2018-01-16 04:02 UTC
